# Docker compose file for Development
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./chatbot:/app/chatbot
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./.pre-commit-config.yaml:/app/.pre-commit-config.yaml
    command: ["tail", "-f", "/dev/null"]  # Run the container indefinitely
