# Docker compose file for Production
services:
  bot:
    image: chatbot
    container_name: chatbot
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:3
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_LOGS_CHANNEL_ID: ${BOT_LOGS_CHANNEL_ID}
      ROLES_MESSAGE_ID: ${ROLES_MESSAGE_ID}
      SERVER_ID: ${SERVER_ID}
      TZ: ${TIMEZONE}
    volumes:
      - ./logs:/app/logs
    command: ["chatbot", "-f", "${DATABASE_PATH}"]
